### ISSUE TITLE
oof: Error 3

### ISSUE THREAD

**Issue by niansa** [Universal-Team/Relaunch#35]
How do I have to boot this file?

All I get is:
"oof: Error 3"

**Comment by SuperSaiyajinStackie** [comment]
First of all...
- Which console?
- Which Version?
- How do you boot it?

**Comment by FlameKat53** [comment]
Please use v4.0.0, not v4.0.0b (bruh edition) if you areusing it

**Comment by niansa** [comment]
> First of all...
> 
>     * Which console?
> 
>     * Which Version?
> 
>     * How do you boot it?

Nintendo DSi LL
4.0.0bruh
godmode9i

**Comment by niansa** [comment]
> Please use v4.0.0, not v4.0.0b (bruh edition) if you are using it

I tried, same error
